# Publications: Template settings file
#
# The working instance of this file must be located in the
# 'Publications/site'. If named other than `settings.yaml´ that name must
# be specified as a command line argument or in the PUBLICATIONS_SETTINGS
# environment variable.
#
# Remember to hide its contents from prying eyes by setting access to
# the settings file such that only the web server is allowed to read it.

# Logging and debug; set to 'true' if needed during development.
TORNADO_DEBUG: false
LOGGING_DEBUG: false

# Base URL for the site; the externally visible URL.
BASE_URL: 'https://publications.whatever.org/'

# Port for the tornado server.
PORT: 8885

# CouchDB database connection setup.

# The URL for this software system to access the CouchDB server.
# The CouchDB server may be on another machine.
DATABASE_SERVER: 'http://localhost:5984/'

# The name of the database in the CouchDB server.
DATABASE_NAME: 'publications'

# The CouchDB account to use for accessing the database.
# It must have read/write priviliges to the database.
DATABASE_ACCOUNT: 'admin'

# The CouchDB account password to use for accessing the database.
DATABASE_PASSWORD: 'secret'

# Login setup. Once set, changing these will invalidate all passwords.
COOKIE_SECRET: 'long random string of characters'
PASSWORD_SALT: 'another long random string of characters'

# Email setup using server running on the host machine.
# EMAIL:
#   HOST: 'localhost'
#   SENDER: '"My Name" <my.name@whatever.site>'

# Email setup using Google server and my personal work account.
# Account with an app-specific password.
MAIL_SERVER: 'smtp.gmail.com'
MAIL_DEFAULT_SENDER: '"Per Kraulis" <per.kraulis@scilifelab.se>'
MAIL_PORT: 587
MAIL_USE_TLS: true
MAIL_USERNAME: 'per.kraulis@scilifelab.se'
MAIL_PASSWORD: 'this must be the app-specific password'
