# Publications: Template settings file
#
# The working instance of this file must be located in the
# 'Publications/site'. If named other than `settings.yaml´ that name must
# be specified as a command line argument or in the PUBLICATIONS_SETTINGS
# environment variable.
#
# Remember to hide its contents from prying eyes by setting
# access such that only the web server is allowed to read it.


# Base URL for the site; the externally visible URL.
BASE_URL: 'https://publications.whatever.org/'

# Port for the tornado server.
PORT: 8885

# Logging and debug.
TORNADO_DEBUG: True
LOGGING_DEBUG: True

# CouchDB database connection setup.

# The URL for this software system to access the CouchDB server.
# The CouchDB server may be on another machine.
DATABASE_SERVER: 'http://localhost:5984/'

# The name of the database in the CouchDB server.
DATABASE_NAME: 'publications'

# The CouchDB account to use for accessing the database.
# It must have read/write priviliges to the database.
DATABASE_ACCOUNT: 'admin'

# The CouchDB account password to use for accessing the database.
DATABASE_PASSWORD: 'secret'

# Login setup. Once set, changing these will invalidate all passwords.
COOKIE_SECRET: 'long random string of characters'
PASSWORD_SALT: 'another long random string of characters'

# Email using server running on the host machine.
EMAIL:
  HOST: 'localhost'
  SENDER: '"My Name" <my.name@whatever.site>'
