FROM python:alpine

RUN apk update && apk upgrade

COPY ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt gunicorn
COPY ./publications /code/publications
RUN mkdir /code/site
WORKDIR /code/publications
ENV PYTHONPATH /code

CMD ["python3", "publications/app_publications.py"]

VOLUME ["/code/site"]
